### ISSUE TITLE
SSL for automation manager

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/meta#221]
### Context
we're using Jenkins deployed to automation.pdap.io, but it's not https. in the past we've used DO's app platform, which handles this automatically.

### Requirements
it seems like it's best to generate a certificate using something like [certbot](https://certbot.eff.org/instructions), turn it into a js keystore, then configure Jenkins with that.

I got to the point where I was making certbot commands in the droplet console, but I try not to enter commands I don't understand outside my own terminal...would rather not mess anything up. Let me know if you need my digital ocean authority to support this.

**Comment by maxachis** [comment]
Begun working on this. pdap.automation.io now redirects to a new droplet that has SSL. It was ultimately easier for me to just start a new droplet rather than try to integrate it into our existing setup and risk something breaking.

I intend for that droplet to also incorporate some other changes discussed in #223: Namely, the use of docker containers and ensuring that setup doesn't require root access and can be done automatically from Jenkins.

**Comment by maxachis** [comment]
SSL has been incorporated, and so this can now be closed!
